Article.create("title"=>"This is my first article", "description"=>"This is my first article description edited", "user_id"=>8)
Article.create("title"=>"Edited 4th", "description"=>"Description of 4th Article", "user_id"=>8)
Article.create("title"=>"This a new article", "description"=>"Description for new article", "user_id"=>8)
Article.create("title"=>"This is a title", "description"=>"Yash Description", "user_id"=>3)
Article.create("title"=>"Sample", "description"=>"Yash this is sample Article", "user_id"=>3)
Article.create("title"=>"Lorem Ipsum", "description"=>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dolor sed viverra ipsum nunc aliquet bibendum enim. In massa tempor nec feugiat.", "user_id"=>3)
Article.create("title"=>"Nam eget neque luctus", "description"=>"Nam eget neque luctus, egestas magna rhoncus, ornare tellus. Integer in enim in velit scelerisque sagittis et in metus. Nullam ac vestibulum ipsum, sed placerat nisl. ", "user_id"=>8)
Article.create("title"=>"Orci varius natoque penatibus", "description"=>"Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin in nisl eros. Interdum et malesuada fames ac ante ipsum primis in faucibus. ", "user_id"=>7)
Article.create("title"=>"Article", "description"=>"Article With ID", "user_id"=>7)
Article.create("title"=>"New Article", "description"=>"Article With User IDD", "user_id"=>3)
Article.create("title"=>"Title", "description"=>"With Debugger", "user_id"=>3)
Article.create("title"=>"New Article", "description"=>"Trying with debug", "user_id"=>3)
Article.create("title"=>"First Article", "description"=>"Description of 1st Article", "user_id"=>4)
Article.create("title"=>"Second Article", "description"=>"Description of 2nd Article", "user_id"=>4)
Article.create("title"=>"Third Article", "description"=>"Description of 3rd Article", "user_id"=>4)
Article.create("title"=>"Third Article", "description"=>"Description of 3rd Article", "user_id"=>7)
Article.create("title"=>"Fourth Article", "description"=>"Description of 4th Article", "user_id"=>7)
Article.create("title"=>"Fifth Article", "description"=>"Description of 5th Article", "user_id"=>7)
Article.create("title"=>"Sixth Article", "description"=>"Description of 6th Article", "user_id"=>7)
Article.create("title"=>"Fifth Article", "description"=>"Description of 5th Article", "user_id"=>4)
Article.create("title"=>"Sixth Article", "description"=>"Description of 6th Article", "user_id"=>4)
Article.create("title"=>"Sed vel commodo est", "description"=>"Nullam vehicula nulla in nibh tristique facilisis. Praesent nec magna posuere, dictum justo tincidunt, hendrerit tortor.", "user_id"=>8)
Article.create("title"=>"Phasellus placerat", "description"=>"Dolor ac mauris aliquam varius. Aenean rhoncus orci eget elit finibus, a viverra felis viverra. Cras quis leo enim. Proin volutpat sapien vitae malesuada volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit", "user_id"=>8)
User.create("username"=>"Jasper", "email"=>"sample@example.com", "password_digest"=>"$2a$12$7JeJqwxfXlIj.OHiOUHu0enrdo72fNA40sYTAOnEFouRwzFdvJ7qK")
User.create("username"=>"Jasper2", "email"=>"jasper2@example.com", "password_digest"=>"$2a$12$KmTcgAtpNSWs7JcmCDElWevmY4PSnBHfRG/OKcRis65zWMtJ9POEy")
User.create("username"=>"Jasper3", "email"=>"jasper3@example.com", "password_digest"=>"$2a$12$RuLHock6qzejLIIjES1rF.Xdcb5bWvLI1AJkXp4b/kaONJavtusDG")
User.create("username"=>"Chrisy", "email"=>"christopher.lloyd@gmail.com", "password_digest"=>"$2a$12$e85ifEPJ58NaUaIboZgtYulX8.1LoaA5KZ3.TaV0xt0u4WWqMzhaC")
