User.create("id"=>3, "username"=>"Jasper", "email"=>"sample@example.com", "password_digest"=>"$2a$12$7JeJqwxfXlIj.OHiOUHu0enrdo72fNA40sYTAOnEFouRwzFdvJ7qK", "admin"=>true)
User.create("id"=>4, "username"=>"jasper2", "email"=>"jasper2@example.com", "password_digest"=>"$2a$12$KmTcgAtpNSWs7JcmCDElWevmY4PSnBHfRG/OKcRis65zWMtJ9POEy", "admin"=>false)
User.create("id"=>7, "username"=>"Jasper3", "email"=>"jasper3@example.com", "password_digest"=>"$2a$12$RuLHock6qzejLIIjES1rF.Xdcb5bWvLI1AJkXp4b/kaONJavtusDG", "admin"=>false)
User.create("id"=>8, "username"=>"Chrisy", "email"=>"christopher.lloyd@gmail.com", "password_digest"=>"$2a$12$e85ifEPJ58NaUaIboZgtYulX8.1LoaA5KZ3.TaV0xt0u4WWqMzhaC", "admin"=>false)
User.create("id"=>10, "username"=>"jasx", "email"=>"jasx@example.com", "password_digest"=>"$2a$12$lQ8AS6McPc7t6Sv38Ck/UeiB.sT/FltSr.LuxylhkcmFGiqEwglLW", "admin"=>false)
User.create("id"=>11, "username"=>"sign", "email"=>"sign@example.com", "password_digest"=>"$2a$12$NTwqc2oSZpWAX5nIMceaEu/iCHO6QHBXddKrGk9JlzcKst2g47GRe", "admin"=>false)
Article.create("id"=>4, "title"=>" Nam pulvinar fermentum lacus", "description"=>"Phasellus congue commodo lacus vel facilisis. Nam pulvinar fermentum lacus, et eleifend nisi feugiat quis. Aenean diam libero, iaculis quis mauris vel, mollis vestibulum lorem. Aliquam augue urna, viverra id iaculis et, congue eget ante. Nullam scelerisque diam eu rutrum hendrerit.", "user_id"=>8)
Article.create("id"=>5, "title"=>"Vel gravida ipsum consequat", "description"=>"Fusce pharetra lobortis dolor, semper pharetra lectus pellentesque sed. Nam elementum lacus a justo auctor dapibus. Etiam justo lorem, dictum in tellus ut, molestie posuere lectus. Phasellus feugiat ligula eu est tempor, vitae tempus purus ornare. Sed rutrum lorem efficitur urna viverra.", "user_id"=>8)
Article.create("id"=>6, "title"=>"Nam pellentesque tortor arcu", "description"=>"Sed suscipit ante suscipit accumsan. Phasellus dolor leo, pretium sed est ac, ullamcorper tincidunt erat. Morbi blandit nisi ipsum, at vehicula lectus vehicula vel.", "user_id"=>3)
Article.create("id"=>11, "title"=>"Quisque ut justo vulputate", "description"=>"Ultricies erat id, semper diam. Integer mi turpis, ultricies at quam non, molestie venenatis velit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. ", "user_id"=>3)
Article.create("id"=>12, "title"=>"Lorem Ipsum", "description"=>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dolor sed viverra ipsum nunc aliquet bibendum enim. In massa tempor nec feugiat.", "user_id"=>3)
Article.create("id"=>13, "title"=>"Nam eget neque luctus", "description"=>"Nam eget neque luctus, egestas magna rhoncus, ornare tellus. Integer in enim in velit scelerisque sagittis et in metus. Nullam ac vestibulum ipsum, sed placerat nisl. ", "user_id"=>4)
Article.create("id"=>14, "title"=>"Orci varius natoque penatibus", "description"=>"Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin in nisl eros. Interdum et malesuada fames ac ante ipsum primis in faucibus. ", "user_id"=>7)
Article.create("id"=>15, "title"=>"Pellentesque nulla sem", "description"=>"Pellentesque nulla sem, hendrerit sit amet mattis vel, dapibus hendrerit nulla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc congue ipsum vitae ex placerat lacinia. Donec pellentesque risus ut quam pellentesque, vitae pellentesque quam sagittis. ", "user_id"=>7)
Article.create("id"=>16, "title"=>"Morbi aliquet", "description"=>"Quam eu auctor maximus, massa neque vestibulum nibh, sit amet volutpat orci lectus non diam. Aliquam sit amet lobortis ligula. Vestibulum lectus eros, sodales ac pretium eget, pellentesque et risus.", "user_id"=>3)
Article.create("id"=>17, "title"=>"Suspendisse sit amet bibendum urna", "description"=>"Fusce eu enim commodo lacus accumsan facilisis. Curabitur eget mi ac turpis volutpat sagittis sed in mauris. Pellentesque eget vulputate nisl, nec consequat nisl.", "user_id"=>3)
Article.create("id"=>18, "title"=>"Duis efficitur", "description"=>"Duis efficitur enim et tristique condimentum. Maecenas luctus, diam et aliquet dignissim, purus ante dapibus dui, sit amet cursus turpis erat at augue. Vivamus sollicitudin sodales metus, sed tincidunt lorem consequat sit amet.", "user_id"=>3)
Article.create("id"=>19, "title"=>"Vivamus aliquam magna", "description"=>"Vivamus aliquam magna ac ligula vulputate vestibulum. Quisque vel ligula quis dolor porttitor ultricies in quis est. Nulla eu urna a diam suscipit pretium vitae in nisi. Vivamus dictum erat vitae felis pharetra consequat nec vitae lectus.", "user_id"=>4)
Article.create("id"=>20, "title"=>"Maecenas semper", "description"=>"Maecenas semper sem bibendum, volutpat urna vitae, rhoncus leo. Sed vehicula odio ac consequat molestie. In quis est semper, commodo quam in, viverra purus. Cras aliquam nulla leo, non sagittis mauris tincidunt at.", "user_id"=>4)
Article.create("id"=>21, "title"=>"Integer cursus", "description"=>"Integer cursus mauris sit amet eros sodales efficitur. Suspendisse laoreet, dolor et elementum commodo, justo tortor pellentesque odio, sit amet porta ligula elit ut diam. Nam vitae mollis nisi, sit amet rutrum mi.", "user_id"=>4)
Article.create("id"=>22, "title"=>"Suspendisse vel nisl non elit sollicitudin viverra", "description"=>"ellentesque tincidunt nulla in augue sollicitudin accumsan. Morbi nunc massa, finibus sit amet mollis non, ultricies sed ex. Nunc tincidunt, ante vel molestie luctus, quam ex faucibus nulla, vel eleifend nunc diam a diam.", "user_id"=>7)
Article.create("id"=>23, "title"=>"Fusce mollis", "description"=>"Fusce mollis, orci nec facilisis auctor, ipsum eros laoreet diam, ac ullamcorper est turpis vel massa. Pellentesque placerat turpis nulla, et facilisis turpis ultrices ut. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.", "user_id"=>7)
Article.create("id"=>24, "title"=>" Aenean sed porttitor neque", "description"=>"Quisque lacinia convallis tellus, sed tempor nunc convallis eu. Proin aliquam bibendum dui, nec sodales mauris rhoncus sit amet. Pellentesque vel dictum nisl, ut tincidunt lorem. Maecenas sodales risus laoreet dapibus bibendum. Etiam urna tortor, placerat ac blandit non, ultricies ut nisl.", "user_id"=>7)
Article.create("id"=>25, "title"=>"Suspendisse et sem", "description"=>"Maecenas non eleifend purus, nec fermentum leo. Suspendisse et sem at ligula ullamcorper faucibus. Sed ornare dui at lacus vulputate, ornare fermentum nulla mattis. Suspendisse hendrerit auctor elit, vel rutrum nisl sodales at. Aenean sem purus, aliquam vitae enim at, aliquam sodales sapien.", "user_id"=>7)
Article.create("id"=>26, "title"=>"Suspendisse potenti", "description"=>"Nunc suscipit nunc eros, ac tincidunt tellus efficitur vitae. Morbi felis nibh, maximus eu dignissim a, egestas et purus. Maecenas luctus aliquet aliquet. Praesent congue quis ligula vel vulputate. Suspendisse potenti.", "user_id"=>4)
Article.create("id"=>27, "title"=>"Praesent cursus auctor posuere", "description"=>"Proin tristique massa quis erat commodo egestas. Nullam quam massa, vehicula at nulla a, laoreet finibus arcu. Cras eu sapien feugiat, semper ipsum ut, elementum lacus. Cras eros justo, euismod sed cursus id, bibendum ac elit. ", "user_id"=>4)
Article.create("id"=>28, "title"=>"Sed vel commodo est", "description"=>"Nullam vehicula nulla in nibh tristique facilisis. Praesent nec magna posuere, dictum justo tincidunt, hendrerit tortor.", "user_id"=>8)
Article.create("id"=>29, "title"=>"Phasellus placerat", "description"=>"Dolor ac mauris aliquam varius. Aenean rhoncus orci eget elit finibus, a viverra felis viverra. Cras quis leo enim. Proin volutpat sapien vitae malesuada volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit", "user_id"=>8)
Article.create("id"=>30, "title"=>"Fusce aliquam turpis", "description"=>"En fermentum nibh ut nisl porta, ut dapibus nulla euismod. Fusce aliquam turpis a ipsum eleifend, quis euismod massa mollis. Fusce quis nisl vel metus venenatis gravida. Donec feugiat, nulla viverra sollicitudin fringilla, enim ipsum consectetur lacus, at aliquet eros tellus eu ante.", "user_id"=>8)
Article.create("id"=>31, "title"=>"Aliquam id magna diam", "description"=>"Aenean luctus tortor nisi, id hendrerit enim egestas a. Phasellus fringilla auctor elit tincidunt faucibus. Curabitur finibus ex quis tempor maximus. Phasellus sed eros vitae lorem viverra porttitor. Morbi rhoncus dictum risus sit amet hendrerit. Curabitur egestas lectus eu nulla finibus aliquam.", "user_id"=>4)
Article.create("id"=>33, "title"=>"Ac placerat vestibulum", "description"=>"Nisl rhoncus mattis rhoncus urna neque viverra justo. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Ipsum dolor sit amet consectetur.", "user_id"=>4)
Category.create("id"=>1, "name"=>"Sports")
Category.create("id"=>2, "name"=>"Programming")
Category.create("id"=>3, "name"=>"Fiction")
Category.create("id"=>4, "name"=>"Science")
Category.create("id"=>5, "name"=>"Romantics Comedy")
Category.create("id"=>6, "name"=>"Lifestyle")
Category.create("id"=>7, "name"=>"Games")
Category.create("id"=>8, "name"=>"Rake")
ArticleCategory.create("id"=>1, "article_id"=>31, "category_id"=>1)
ArticleCategory.create("id"=>2, "article_id"=>31, "category_id"=>8)
ArticleCategory.create("id"=>3, "article_id"=>12, "category_id"=>8)
ArticleCategory.create("id"=>4, "article_id"=>33, "category_id"=>5)
ArticleCategory.create("id"=>5, "article_id"=>33, "category_id"=>6)
ArticleCategory.create("id"=>6, "article_id"=>33, "category_id"=>8)
ArticleCategory.create("id"=>7, "article_id"=>13, "category_id"=>2)
ArticleCategory.create("id"=>8, "article_id"=>13, "category_id"=>3)
ArticleCategory.create("id"=>9, "article_id"=>13, "category_id"=>5)
ArticleCategory.create("id"=>10, "article_id"=>6, "category_id"=>4)
ArticleCategory.create("id"=>11, "article_id"=>6, "category_id"=>7)
ArticleCategory.create("id"=>12, "article_id"=>4, "category_id"=>2)
ArticleCategory.create("id"=>13, "article_id"=>4, "category_id"=>3)
ArticleCategory.create("id"=>14, "article_id"=>4, "category_id"=>4)
ArticleCategory.create("id"=>15, "article_id"=>5, "category_id"=>4)
ArticleCategory.create("id"=>16, "article_id"=>5, "category_id"=>5)
ArticleCategory.create("id"=>17, "article_id"=>5, "category_id"=>6)
ArticleCategory.create("id"=>18, "article_id"=>11, "category_id"=>2)
ArticleCategory.create("id"=>19, "article_id"=>11, "category_id"=>3)
ArticleCategory.create("id"=>20, "article_id"=>14, "category_id"=>4)
ArticleCategory.create("id"=>21, "article_id"=>14, "category_id"=>5)
ArticleCategory.create("id"=>22, "article_id"=>15, "category_id"=>2)
ArticleCategory.create("id"=>23, "article_id"=>15, "category_id"=>4)
ArticleCategory.create("id"=>24, "article_id"=>16, "category_id"=>4)
ArticleCategory.create("id"=>25, "article_id"=>16, "category_id"=>5)
ArticleCategory.create("id"=>26, "article_id"=>17, "category_id"=>4)
ArticleCategory.create("id"=>27, "article_id"=>18, "category_id"=>2)
ArticleCategory.create("id"=>28, "article_id"=>18, "category_id"=>3)
ArticleCategory.create("id"=>29, "article_id"=>19, "category_id"=>5)
ArticleCategory.create("id"=>30, "article_id"=>19, "category_id"=>6)
ArticleCategory.create("id"=>31, "article_id"=>24, "category_id"=>5)
ArticleCategory.create("id"=>32, "article_id"=>24, "category_id"=>6)
ArticleCategory.create("id"=>33, "article_id"=>20, "category_id"=>5)
ArticleCategory.create("id"=>34, "article_id"=>20, "category_id"=>6)
ArticleCategory.create("id"=>35, "article_id"=>21, "category_id"=>4)
ArticleCategory.create("id"=>36, "article_id"=>21, "category_id"=>5)
ArticleCategory.create("id"=>37, "article_id"=>22, "category_id"=>1)
ArticleCategory.create("id"=>38, "article_id"=>22, "category_id"=>2)
ArticleCategory.create("id"=>39, "article_id"=>22, "category_id"=>5)
ArticleCategory.create("id"=>40, "article_id"=>23, "category_id"=>6)
ArticleCategory.create("id"=>41, "article_id"=>23, "category_id"=>7)
ArticleCategory.create("id"=>42, "article_id"=>25, "category_id"=>6)
ArticleCategory.create("id"=>43, "article_id"=>25, "category_id"=>7)
ArticleCategory.create("id"=>44, "article_id"=>26, "category_id"=>5)
ArticleCategory.create("id"=>45, "article_id"=>26, "category_id"=>6)
ArticleCategory.create("id"=>46, "article_id"=>27, "category_id"=>3)
ArticleCategory.create("id"=>47, "article_id"=>28, "category_id"=>2)
ArticleCategory.create("id"=>48, "article_id"=>28, "category_id"=>3)
ArticleCategory.create("id"=>49, "article_id"=>29, "category_id"=>1)
ArticleCategory.create("id"=>50, "article_id"=>29, "category_id"=>2)
ArticleCategory.create("id"=>51, "article_id"=>30, "category_id"=>7)
ArticleCategory.create("id"=>52, "article_id"=>30, "category_id"=>8)
